version: '3.8'

services:

  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "5000:8080"    # Host 5000 maps to container 8080 to avoid conflict with Jenkins
    environment:
      - MONGO_URL=mongodb://mean-mongo:27017/meanDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mean-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
